# Generated by Django 5.1.1 on 2024-10-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="apartment_number",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="HCS.apartment",
                    ),
                ),
            ],
        ),
    ]
