# Generated by Django 5.1.1 on 2024-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCS", "0003_apartment_last_payment_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="address",
            new_name="street",
        ),
        migrations.AddField(
            model_name="house",
            name="house_number",
            field=models.IntegerField(default=1),
        ),
    ]
